spring:
  application:
    name: bragdoc
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DB_URL:}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8080

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: https://generativelanguage.googleapis.com/v1beta
    model: gemini-flash-latest

logging:
  level:
    bragdoc: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}

github:
  oauth:
    client-id: ${GITHUB_OAUTH_CLIENT_ID:}
    client-secret: ${GITHUB_OAUTH_CLIENT_SECRET:}
    redirect-uri: ${GITHUB_OAUTH_REDIRECT_URI:http://localhost:8080/api/auth/callback}
    frontend-redirect-uri: ${OAUTH_FRONTEND_REDIRECT:http://localhost:4200/auth-callback}

jwt:
  secret: ${JWT_SECRET}

app:
  cookie:
    domain: ${APP_COOKIE_DOMAIN}
    secure: ${APP_COOKIE_SECURE}
    same-site: ${APP_COOKIE_SAME_SITE}
